services:
  server:
    build:
      context: .
      dockerfile: src/main/java/server/Dockerfile.server
    ports:
      - "1234:1234"

  client1:
    build:
      context: .
      dockerfile: src/main/java/client/Dockerfile.client
    depends_on:
      - server

