services:
  server:
    build:
      context: .
      dockerfile: src/main/java/server/Dockerfile.server
    container_name: blackjack-server
    ports:
      - "1234:1234"
    restart: unless-stopped

  client1:
    build:
      context: .
      dockerfile: src/main/java/client/Dockerfile.client
    container_name: blackjack-client1
    depends_on:
      - server
    stdin_open: true
    tty: true

  client2:
    build:
      context: .
      dockerfile: src/main/java/client/Dockerfile.client
    container_name: blackjack-client2
    depends_on:
      - server
    stdin_open: true
    tty: true

